// Generated by CoffeeScript 1.10.0
UI.registerHelper("activeRouteClass", function(routeName) {
  var ref, ref1;
  if (((ref = Router.current()) != null ? (ref1 = ref.route) != null ? ref1.getName() : void 0 : void 0) === routeName) {
    return "active";
  }
});
