// Generated by CoffeeScript 1.10.0
Template.viewprofile.helpers({
  raw: function() {
    return JSON.stringify(this, null, 2);
  },
  ownProfile: function() {
    return Meteor.userId() === this._id;
  },
  email: function() {
    return getEmail(this);
  }
});
