// Generated by CoffeeScript 1.10.0
Template.specimenbuttoncell.helpers({
  "collectionId": function() {
    let currentRoute = Router.current();
    if (currentRoute && currentRoute.params) {
      return currentRoute.params._id;
    }
  },
  "specimenId": function() {
    return this._id;
  }
});
