// Generated by CoffeeScript 1.10.0
Template.specimenbuttoncell.helpers({
  "collectionId": function() {
    var ref, ref1;
    return (ref = Router.current()) != null ? (ref1 = ref.params) != null ? ref1._id : void 0 : void 0;
  },
  "specimenId": function() {
    return this._id;
  }
});
